chore(ci): verify Quay credentials availability (#20495)
At the moment all pull requests created by Dependabot fails when trying
to push Docker images to Quay.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,6 +85,17 @@ jobs:
         if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
         run: yarn nx run server:package
 
+      - name: Verify Quay credentials availability
+        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
+        env:
+          DOCKER_PASSWORD: ${{ secrets.WEBTEAM_QUAY_PASSWORD }}
+          DOCKER_USERNAME: ${{ secrets.WEBTEAM_QUAY_USERNAME }}
+        run: |
+          if [[ -z "${DOCKER_USERNAME}" || -z "${DOCKER_PASSWORD}" ]]; then
+            echo "Missing Quay credentials. For Dependabot pull requests, configure WEBTEAM_QUAY_USERNAME and WEBTEAM_QUAY_PASSWORD as Dependabot secrets."
+            exit 1
+          fi
+
       - name: Push PR Docker image
         if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
         env:
