github cli

diff --git a/.github/workflows/precommit.yml b/.github/workflows/precommit.yml
--- a/.github/workflows/precommit.yml
+++ b/.github/workflows/precommit.yml
@@ -53,20 +53,20 @@ jobs:
           name: 'build-artifact'
           path: '${{env.BUILD_DIR}}${{env.BUILD_ARTIFACT}}'
 
-      - name: Fetch PR details
-        id: pr_details
-        uses: octokit/request-action@v2.x
-        with:
-          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Check total PR additions
         id: check_additions
         run: |
-          total_additions=$(grep -o '"additions": *[0-9]*' <<< '${{ steps.pr_details.outputs.data }}' | sed -E 's/.*: *([0-9]+)/\1/')
+          total_additions=$(gh api -H "Accept: application/vnd.github.v3+json" \
+                                "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
+                                | jq -r '.additions')
+          if [ -z "$total_additions" ] || [ "$total_additions" = "null" ]; then
+            echo "Error: Could not extract additions"
+            exit 1
+          fi
           echo "Found total additions: $total_additions"
           echo "total_additions=$total_additions" >> $GITHUB_OUTPUT
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   deploy_to_aws:
     name: 'Deploy to live environments'
