restore initial organization

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -174,7 +174,6 @@ jobs:
       - uses: azure/setup-helm@v4
         with:
           version: '3.12.2'
-        id: install
 
       - name: Generate helm chart version
         shell: bash
@@ -205,13 +204,56 @@ jobs:
 
           helm s3 push webapp-*.tgz charts-webapp
 
-      - uses: ./.github/composite-actions/publish-wire-builds
+      - name: Check out wire-builds
+        uses: actions/checkout@v4
         with:
-          target_branch: ${{matrix.target_branch}}
-          chart_version: ${{steps.generate_chart_version.outputs.chart_version}}
-          image_tag: ${{needs.build.outputs.image_tag}}
-          release_name: ${{needs.build.outputs.release_name}}
-          gh_token: ${{secrets.WIRE_BUILDS_WRITE_ACCESS_GH_TOKEN}}
+          repository: wireapp/wire-builds
+          token: ${{secrets.WIRE_BUILDS_WRITE_ACCESS_GH_TOKEN}}
+          ref: ${{matrix.target_branch}}
+          fetch-depth: 1
+
+      - name: Create new build in wire-build
+        shell: bash
+        run: |
+          set -eo pipefail
+
+          chart_version="${{needs.build.outputs.chart_version}}"
+          image_tag="${{needs.build.outputs.image_tag}}"
+
+          git config --global user.email "zebot@users.noreply.github.com"
+          git config --global user.name "Zebot"
+
+          for retry in $(seq 3); do
+            (
+            set -e
+
+            if (( retry > 1 )); then
+            echo "Retrying..."
+            fi
+
+            git fetch --depth 1 origin "${{ matrix.target_branch }}"
+            git checkout "${{ matrix.target_branch }}"
+            git reset --hard @{upstream}
+
+            build_json=$(cat ./build.json | \
+              ./bin/set-chart-fields webapp \
+              "version=$chart_version" \
+              "repo=https://s3-eu-west-1.amazonaws.com/public.wire.com/charts-webapp" \
+              "meta.appVersion=$image_tag" \
+              "meta.commitURL=${{github.event.head_commit.url}}" \
+              "meta.commit=${{github.event.head_commit.id}}" \
+              | ./bin/bump-prerelease )
+            echo "$build_json" > ./build.json
+
+            git add build.json
+            git commit -m "Bump webapp to $chart_version"
+
+            ) && break
+          done
+          if (( $? != 0 )); then
+              echo "Retrying didn't help. Failing the step."
+              exit 1
+          fi
 
   #FUTUREWORK: Remove this job once production builds are based on wireapp/wire-builds
   update_helm_chart:
